namespace dinospace
{
    public static class DinosaurData
    {
        public static List<Dinosaur> GetAll() => new List<Dinosaur>
            {
                new Dinosaur
                {
                    Name = "T. Rex",
                    Pronunciation = "tie-ran-uh-saw-ruhs reks",
                    Meaning = "Tyrant Lizard King",
                    Era = "Late Cretaceous Period",
                    Group = "Theropod",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "The fearsome king of the dinosaurs",
                    Length = "42 feet",
                    Height = "13 feet",
                    Weight = "7500kg",
                    Speed = "20km/h",
                    Strength = 95,
                    ImageFile = "trex.png",
                    AboutText = "Tyrannosaurus Rex was one of the largest and most powerful meat eating dinosaurs to walk the Earth. It lived around 66 to 68 million years ago in what is now North America. With its enormous skull, powerful jaws, and extremely sharp teeth, the T. Rex was one of the top predators of its time.",
                    KeyFeaturesText = "T. Rex had powerful legs, a gigantic head, and a long tail which helped it balance while moving. Its jaws could deliver one of the strongest bites of any land animal in history. Although known for their tiny arms, they were very muscular and helped hold prey, such as triceratops.",
                    LifeEnvironmentText = "T. Rex lived in river valleys, forests, and coastal plains in the Late Cretaceous Period. These environments held a variety of plants, smaller dinosaurs, and large plant eating species that served as prey. The T. Rex was the apex predator of its time, so nothing stood in its way.",
                    BehaviourText = "T. Rex was both a hunter and scavenger. With its excellent sense of smell, strong vision, and powerful bite force, it was well adapted for ambush hunting and dominating its ecosystem.",
                    FunFactsText = "• T. Rex had teeth up to 12 inches long.\n• Its bite force was around 12,800 pounds — like several cars pressing down on its jaws — strong enough to crush solid bone.\n• T. Rex's arms were so short it couldn't even reach its own mouth — but they could curl 200kg, stronger than most humans.\n• Baby and juvenile T. Rex may have had feathers growing up.\n• More than 50 T. Rex skeletons have been discovered by scientists."
                },
                new Dinosaur
                {
                    Name = "Spinosaurus",
                    Pronunciation = "spai-now-saw-ruhs",
                    Meaning = "Spine Lizard",
                    Era = "Mid Cretaceous Period",
                    Group = "Theropod",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "The longest meat-eater ever to walk the Earth",
                    Length = "50 feet",
                    Height = "18 feet",
                    Weight = "7000kg",
                    Speed = "20km/h",
                    Strength = 90,
                    ImageFile = "spinosaurus.png",
                    AboutText = "Spinosaurus was the longest meat eating dinosaur on Earth. It lived around 95 to 100 million years ago in what is now North Africa. Unlike other large theropods, Spinosaurus spent much of its time near rivers and lakes, to catch fish with its sharp teeth and long snout.",
                    KeyFeaturesText = "Spinosaurus had its long crocodile-like snout, cone-like teeth for gripping slippery prey, and a huge sail on its back to attract mates and intimidate rivals, which also helped with swimming. It also had strong arms with large claws and a paddle-like tail which helped it move through water.",
                    LifeEnvironmentText = "Spinosaurus lived in river systems, mangrove forests, swamps, and coastal wetlands. These habitats were home to fish, crocodile-like reptiles, and other similar prey. Since the Spinosaurus were apex predators, nothing ate them.",
                    BehaviourText = "Spinosaurus was a semi-aquatic dinosaur which spent most of its time hunting around and in water. It used its snout to detect prey and could also swim efficiently with its powerful tail. Though it mainly ate fish, it also hunted smaller dinosaurs and scavenged when there were opportunities.",
                    FunFactsText = "• Spinosaurus was the longest meat-eating dinosaur ever discovered.\n• It spent more time in water than on land.\n• Its jaws were similar to those of modern crocodiles.\n• Scientists believe it was one of the first known swimming dinosaurs.\n• Spinosaurus fossils were first discovered in Egypt in 1912."
                },
                new Dinosaur
                {
                    Name = "Megalodon",
                    Pronunciation = "meh-guh-luh-daan",
                    Meaning = "Big Tooth",
                    Era = "Early Miocene to Pliocene Period",
                    Group = "Shark",
                    Diet = "Carnivore",
                    Category = "Sea",
                    ShortDescription = "A shark the size of a school bus",
                    Length = "60 feet",
                    Width = "8 feet",
                    Weight = "50,000kg",
                    Speed = "20km/h",
                    Strength = 98,
                    ImageFile = "megalodon.png",
                    AboutText = "Megalodon was the largest shark to live in Earth's oceans. It lived 3.6 to 23 million years ago, during the Miocene and Pliocene eras. Megalodon was one of the most fearsome predators in history due to its enormous size, powerful jaws, and massive teeth. It hunted large marine animals, including whales, and ruled the oceans for millions of years.",
                    KeyFeaturesText = "Megalodon had an enormous mouth filled with rows of razor-sharp teeth designed for cutting through flesh and bone. Its powerful body and strong tail made it a great swimmer even with its massive size. It looked very similar to the modern great white shark, scaled up, and with a much more robust body.",
                    LifeEnvironmentText = "Megalodon lived in warm oceans around the world, near coastlines where food was abundant. These marine environments had plenty of seals, dolphins, whales, and large fish that served as prey. As the strongest apex predator of its time, Megalodon had little to no natural threats and dominated ocean ecosystems.",
                    BehaviourText = "Megalodon was an active hunter that relied on its speed, strength, and surprise attacks to catch prey. Scientists believe it targeted the tails and fins of large whales to disable them before delivering a fatal bite. Its excellent sense of smell helped it locate prey over long distances in the large ocean.",
                    FunFactsText = "• Megalodon teeth could grow over 7 inches long.\n• It had a bite force estimated at over 40,000 pounds, the strongest bite force of any creature on Earth.\n• Megalodon had to eat over 1000kg of food each day just to survive.\n• Scientists know about Megalodon mainly from its fossilized teeth and vertebrae.\n• Megalodon actually lived after the dinosaurs went extinct, around 43 million years after."
                },
                new Dinosaur
                {
                    Name = "Velociraptor",
                    Pronunciation = "vuh-laa-sr-ap-tr",
                    Meaning = "Speedy Robber",
                    Era = "Late Cretaceous Period",
                    Group = "Raptor",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "A feathered hunter as small as a turkey",
                    Length = "6.5 feet",
                    Height = "1.5 feet",
                    Weight = "17kg",
                    Speed = "45km/h",
                    Strength = 25,
                    ImageFile = "velociraptor.png",
                    AboutText = "Velociraptor was a small but very intelligent carnivorous dinosaur that lived 71 to 75 million years ago in what is now China and Mongolia. Despite being famous as a large predator in movies, Velociraptors were only the size of a turkey. Even so, they were fast, agile hunters that used their sharp claws and natural instincts to catch prey.",
                    KeyFeaturesText = "Velociraptor had a lightweight body, sickle-shaped claws on each foot that grew up to 3 inches, and long legs built for running. Scientists believe it was covered in feathers, making it closer to modern birds than reptiles. Its long tail helped it balance when running and making sharp turns.",
                    LifeEnvironmentText = "Velociraptor lived in dry deserts, sand dunes, and arid plains in the Late Cretaceous Period. These environments were home to small dinosaurs, lizards, and mammals that served as prey. The Velociraptor was often prey to large therapods such as Tarbosaurus.",
                    BehaviourText = "Velociraptor was a quick and active hunter, which compensated for its small size. Scientists believe it used its sharp claws to grip and wound prey, and used its jaws to deliver fast bites. Its bite was fairly weak, so it relied mainly on its claws to bring down prey.",
                    FunFactsText = "• Velociraptor was covered in feathers.\n• It was only about the size of a turkey.\n• There's no scientific evidence they hunted in packs.\n• Fossils have been found showing a Velociraptor fighting a Protoceratops.\n• Velociraptor was one of the most intelligent dinosaurs."
                },
                new Dinosaur
                {
                    Name = "Triceratops",
                    Pronunciation = "trai-seh-ruh-tops",
                    Meaning = "Three-Horned Face",
                    Era = "Late Cretaceous Period",
                    Group = "Ceratopsian",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "Three sharp horns and a giant frill",
                    Length = "28 feet",
                    Height = "10 feet",
                    Weight = "10,000kg",
                    Speed = "30km/h",
                    Strength = 70,
                    ImageFile = "triceratops.png",
                    AboutText = "Triceratops was one of the most famous plant eating dinosaurs to ever live. It lived around 66 to 68 million years ago in what is now North America. With its three large horns, enormous skull, and powerful body, Triceratops was well equipped to defend itself against predators and eat tough vegetation.",
                    KeyFeaturesText = "Triceratops had two long horns just above its eyes, a shorter horn on its nose, and a large, bony frill which protected its neck. Its strong beak was excellent for cutting through tough plants, while rows of teeth helped it chew food efficiently. Its sturdy body and strong legs made it one of the strongest herbivores of the Late Cretaceous.",
                    LifeEnvironmentText = "Triceratops lived in forests, river valleys, floodplains, and woodlands. These environments were abundant in ferns, palms, cycads, and other low growing plants to eat. Triceratops shared its habitat with many other dinosaurs, including its predators such as T. Rex.",
                    BehaviourText = "Triceratops spent most of its day eating plants and moving through areas with fresh vegetation. Scientists believe it may have lived alone or in small groups. When threatened, it used its horn and sturdy body to defend itself, making it a very difficult target for enemies.",
                    FunFactsText = "• Triceratops had one of the largest skulls of any land animal, measuring up to 8 feet long.\n• Its two long brow horns could each grow over 3 feet long, while the shorter nose horn sat just above its beak.\n• Triceratops often managed to defend themselves from T. Rex.\n• Triceratops lived up to 30 years.\n• Triceratops fossils are among the most common fossils found."
                },
                new Dinosaur
                {
                    Name = "Pteranodon",
                    Pronunciation = "tuh-ra-nuh-daan",
                    Meaning = "Toothless Wing",
                    Era = "Late Cretaceous Period",
                    Group = "Pterosaur",
                    Diet = "Carnivore",
                    Category = "Flying",
                    ShortDescription = "A flying reptile with enormous wings",
                    Length = "23 feet",
                    Height = "6 feet",
                    Weight = "25kg",
                    Speed = "80km/h",
                    Strength = 20,
                    ImageFile = "pteranodon.png",
                    AboutText = "Pteranodon was one of the largest flying reptiles on Earth. It lived around 75 to 85 million years ago during the Late Cretaceous Period in what is now North America. Despite often being called a dinosaur, Pteranodon was a pterosaur, a group of flying reptiles that lived alongside the dinosaurs. With its enormous wingspan and lightweight body, it spent most of its life soaring over ancient seas for food.",
                    KeyFeaturesText = "Pteranodon had a long pointed beak without teeth, a large head crest, and a wingspan stretching over 23 feet. Its hollow bones made it lightweight and adapted for flight. The crest helped with balance, steering, and attracting mates.",
                    LifeEnvironmentText = "Pteranodon lived along coastlines, islands, beaches, and shallow inland seas. These environments were abundant with fish and other marine animals that served as prey. It spent most of its time flying over water and nesting in large colonies on rocky shores and cliffs. It was preyed on by large marine animals such as Tylosaurus and prehistoric sharks.",
                    BehaviourText = "Pteranodon was an expert glider that used ocean winds to travel long distances with minimal effort. It hunted by diving down to catch fish at the water's surface with its long beak. Scientists believe it spent most of its time in the air and gathered in groups during breeding seasons.",
                    FunFactsText = "• Pteranodon was not a dinosaur but a flying reptile.\n• Its wingspan could reach over 23 feet, wider than many small airplanes.\n• It had no teeth despite being a carnivore.\n• The large crest on its head may have helped with steering and display.\n• Pteranodon's hollow bones made it super lightweight."
                },
                new Dinosaur
                {
                    Name = "Brachiosaurus",
                    Pronunciation = "brae-kee-uh-saw-ruhs",
                    Meaning = "Arm Lizard",
                    Era = "Late Jurassic Period",
                    Group = "Sauropod",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "A gentle giant taller than a house",
                    Length = "80 feet",
                    Height = "40 feet",
                    Weight = "50,000kg",
                    Speed = "15km/h",
                    Strength = 60,
                    ImageFile = "brachiosaurus.png",
                    AboutText = "Brachiosaurus was one of the tallest dinosaurs to ever walk the Earth. It lived around 150 to 154 million years ago during the Late Jurassic Period in what is now North America. Unlike many other long necked dinosaurs, Brachiosaurus had longer front legs than back legs, which helped it reach food high above the ground.",
                    KeyFeaturesText = "Brachiosaurus had an extremely long neck, massive body, and thick legs built to support its weight. Since its front legs were longer than its back legs, its shoulders sat higher than its hips. This unique body shape allowed it to browse treetops that few other dinosaurs could reach.",
                    LifeEnvironmentText = "Brachiosaurus lived in floodplains, forests, river valleys, and open woodlands. Its diet consisted of tall conifer trees, cycads, ferns, and other plants that provided a constant food supply. Due to its enormous size, adult Brachiosaurus had no natural predators, however baby or juvenile Brachiosaurus were regularly hunted by theropods such as Allosaurus.",
                    BehaviourText = "Brachiosaurus spent most of its day eating leaves and vegetation from tall trees. Scientists believe it moved slowly across large areas in search of food and may have lived in small groups. It had to eat 750 kilograms of vegetation daily to survive.",
                    FunFactsText = "• Brachiosaurus could reach leaves over 40 feet above the ground.\n• It weighed as much as 9 African elephants.\n• Its heart may have weighed over 400kg to pump blood up its long neck.\n• Brachiosaurus had peg-like teeth only used for stripping leaves. It couldn't chew and swallowed everything whole.\n• It could live up to 80 years old."
                },
                new Dinosaur
                {
                    Name = "Stegosaurus",
                    Pronunciation = "steh-guh-saw-ruhs",
                    Meaning = "Roofed Lizard",
                    Era = "Late Jurassic Period",
                    Group = "Stegosaur",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "Bony plates and a deadly spiked tail",
                    Length = "25 feet",
                    Height = "12 feet",
                    Weight = "5000kg",
                    Speed = "7km/h",
                    Strength = 55,
                    ImageFile = "stegosaurus.png",
                    AboutText = "Stegosaurus lived around 145 to 155 million years ago during the Late Jurassic Period in what is now North America and Europe. With its distinctive rows of plates and spiked tail, Stegosaurus is one of the most recognizable dinosaurs ever discovered.",
                    KeyFeaturesText = "Stegosaurus had two rows of large bony plates going down its back and four long spikes on its tail, known as a thagomizer. Its small head contained a beak for clipping plants, while its powerful legs helped support its bulky body. The plates may have been used for display, identifying individuals, or to help regulate body temperature.",
                    LifeEnvironmentText = "Stegosaurus lived in open woodlands, floodplains, forests, and river valleys. These environments had plenty of ferns, cycads, horsetails, and other low growing plants that made up its diet. It lived near giant sauropods and predators such as Allosaurus and Ceratosaurus, which occasionally hunted younger or weaker individuals.",
                    BehaviourText = "Stegosaurus spent most of its day slowly grazing for food close to the ground. Although not a fast dinosaur, it could defend itself effectively using its powerful spiked tail. Scientists believe it may have lived alone or in small groups and relied on its size and defensive weapons to deter predators.",
                    FunFactsText = "• Stegosaurus had a brain about the size of a walnut.\n• Its tail spikes could grow over 3 feet long.\n• Its back plates were too thin to be armour — scientists think they were used to show off or help control body heat.\n• Stegosaurus is the state fossil of Colorado, USA.\n• When cornered, it could whip its tail with the force of a car crash to deliver deep, crushing puncture wounds."
                },
                new Dinosaur
                {
                    Name = "Mosasaurus",
                    Pronunciation = "moh-zuh-saw-ruhs",
                    Meaning = "Meuse Lizard",
                    Era = "Late Cretaceous Period",
                    Group = "Mosasaur",
                    Diet = "Carnivore",
                    Category = "Sea",
                    ShortDescription = "A giant lizard that ruled the seas",
                    Length = "40 feet",
                    Width = "6 feet",
                    Weight = "12,000kg",
                    Speed = "48km/h",
                    Strength = 88,
                    ImageFile = "mosasaurus.png",
                    AboutText = "Mosasaurus was one of the largest and most powerful marine reptiles to ever live. It lived around 66 to 82 million years ago during the Late Cretaceous Period in oceans around the world. Despite often being called a dinosaur, Mosasaurus was a giant marine lizard related to modern monitor lizards and snakes. It needed to surface regularly to breathe air, similar to modern whales and dolphins.",
                    KeyFeaturesText = "Mosasaurus had a long streamlined body, powerful paddle-like flippers, and a strong tail that propelled it through water. Its jaws were double-hinged, which allowed it to swallow large prey whole. Rows of sharp, backward-curving teeth helped it grip slippery prey such as fish, ammonites, sea turtles, and other marine reptiles.",
                    LifeEnvironmentText = "Mosasaurus lived in warm shallow seas, coastal waters, and inland oceans. These marine ecosystems were filled with fish, sharks, ammonites, turtles, and other reptiles that served as prey. As one of the top predators of its environment, adult Mosasaurus had no natural enemies.",
                    BehaviourText = "Mosasaurus was an active hunter that relied on its speed, strength, and ambush attacks to capture prey. It could rapidly accelerate through the water using its powerful tail and hunted anything it could overpower. Scientists believe it spent most of its life in the open ocean, only occasionally approaching shallow coastal waters.",
                    FunFactsText = "• Mosasaurus was more related to a snake than a dinosaur.\n• Its jaws contained a second set of teeth on the roof of its mouth to help swallow prey.\n• It could grow longer than a school bus.\n• Fossils of Mosasaurus have been found on every continent, including Antarctica. No beach was safe.\n• Mosasaurus is simply the most famous of its group, Mosasaur. This group includes other prehistoric beasts such as the Tylosaurus."
                },
                new Dinosaur
                {
                    Name = "Liopleurodon",
                    Pronunciation = "lai-uh-plaw-ruh-daan",
                    Meaning = "Smooth-Sided Teeth",
                    Era = "Mid Jurassic Period",
                    Group = "Pliosaur",
                    Diet = "Carnivore",
                    Category = "Sea",
                    ShortDescription = "A massive hunter of the ancient oceans",
                    Length = "23 feet",
                    Width = "9 feet",
                    Weight = "2000kg",
                    Speed = "30km/h",
                    Strength = 80,
                    ImageFile = "liopleurodon.png",
                    AboutText = "Liopleurodon was a powerful marine reptile that lived around 155 to 160 million years ago during the Middle Jurassic Period. It was one of the top predators of the ancient seas that covered parts of Europe. With its massive head, strong jaws, and powerful flippers, it was perfectly adapted for hunting large marine prey.",
                    KeyFeaturesText = "Liopleurodon had a huge skull filled with long, sharp, conical teeth designed for gripping and tearing prey. Its body was streamlined with four strong flippers that allowed it to swim with speed and agility. Unlike long-necked marine reptiles, it had a short neck and a powerful build for sudden bursts of movement.",
                    LifeEnvironmentText = "Liopleurodon lived in warm, shallow seas that covered what is now England and parts of Europe. These waters were home to fish, squid-like creatures, and other marine reptiles. As an apex predator, it had no natural enemies in its ecosystem.",
                    BehaviourText = "Liopleurodon was an ambush predator that relied on stealth and sudden acceleration to catch prey. It likely used its strong sense of smell and vision to detect animals in the water, striking quickly with its powerful jaws before the prey could escape.",
                    FunFactsText = "• Some fossils grouped under 'Liopleurodon' could actually be different related animals mislabeled together.\n• It had one of the strongest bites among marine reptiles of its time, around 17,000 pounds.\n• Its nostrils were used for smelling underwater, not breathing.\n• Its sensory system likely relied heavily on vibration.\n• Fossils were relatively rare, so size estimates are often debated."
                },
                new Dinosaur
                {
                    Name = "Giganotosaurus",
                    Pronunciation = "jai-ga-nuh-tuh-saw-ruhs",
                    Meaning = "Giant Southern Lizard",
                    Era = "Mid Cretaceous Period",
                    Group = "Theropod",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "Even longer than the mighty T. Rex",
                    Length = "43 feet",
                    Height = "13 feet",
                    Weight = "8000kg",
                    Speed = "30km/h",
                    Strength = 92,
                    ImageFile = "giganotosaurus.png",
                    AboutText = "Giganotosaurus was one of the largest meat-eating dinosaurs ever discovered, even bigger than Tyrannosaurus Rex in length. It lived around 97 to 99 million years ago in what is now Argentina. As an apex predator, it dominated its environment and hunted some of the largest dinosaurs that ever lived.",
                    KeyFeaturesText = "Giganotosaurus had a huge skull lined with sharp teeth designed for slicing through flesh. Its long legs made it a fast and efficient hunter for its size, while its strong tail helped with balance. Although slightly lighter-built than T. Rex, its sheer length made it one of the most formidable predators of the Cretaceous.",
                    LifeEnvironmentText = "Giganotosaurus lived in forests, floodplains, and river valleys of ancient South America. This region was home to enormous herbivores such as Argentinosaurus, which made up a large part of its diet. It shared its ecosystem with other predators but sat near the top of the food chain, so it had no natural predators.",
                    BehaviourText = "Giganotosaurus is believed to have been an active predator that relied on speed and coordination to take down large prey. Giganotosaurus was likely a solitary hunter, though some scientists debate whether it may have occasionally cooperated with others to take down massive prey. It likely used ambush tactics rather than prolonged chases.",
                    FunFactsText = "• Giganotosaurus had a brain the size of a banana.\n• It would bleed out its prey to kill them due to its relatively weaker bite force.\n• Its fossils are rare, so we still don't know much about it.\n• Scientists suggest it could have had camouflage coloration for ambush hunting.\n• Giganotosaurus wasn't discovered until 1993."
                },
                new Dinosaur
                {
                    Name = "Carnotaurus",
                    Pronunciation = "kaar-noh-taw-ruhs",
                    Meaning = "Meat-Eating Bull",
                    Era = "Late Cretaceous Period",
                    Group = "Theropod",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "A horned predator built for speed",
                    Length = "27 feet",
                    Height = "9 feet",
                    Weight = "2000kg",
                    Speed = "54km/h",
                    Strength = 68,
                    ImageFile = "carnotaurus.png",
                    AboutText = "Carnotaurus was a fast, lightweight carnivorous dinosaur that lived around 69 to 72 million years ago in what is now South America. It is best known for its distinctive bull-like horns above its eyes, making it one of the most unusual large theropods. Despite its size, it was built for speed rather than brute strength.",
                    KeyFeaturesText = "Carnotaurus had two thick horns above its eyes, a deep skull, and extremely short forearms. It likely had rough, scale-like skin instead of feathers. Its powerful legs and stiff tail helped stabilize it at high speeds. It had a relatively strong bite force for its size.",
                    LifeEnvironmentText = "Carnotaurus lived in semi-arid plains, forests, and floodplain environments in Argentina. These areas had a variety of herbivorous dinosaurs and smaller prey animals. As an apex predator in its region, it occupied the top of the food chain, so it had no natural predators.",
                    BehaviourText = "Carnotaurus was a fast pursuit predator that likely relied on speed and surprise attacks rather than long chases. Its vision was adapted for depth perception, suggesting it was an active hunter. Its weak arms meant it depended heavily on its jaws to capture and kill prey.",
                    FunFactsText = "• Carnotaurus had the smallest arms of any known large predator dinosaur.\n• It is one of the only large meat-eaters known to have true horns above its eyes.\n• Its horns likely helped in combat or display.\n• Despite having a weak bite force, Carnotaurus could snap its jaws shut faster than almost any other predatory dinosaur.\n• It is one of the few large theropods known from a nearly complete skeleton."
                },
                new Dinosaur
                {
                    Name = "Allosaurus",
                    Pronunciation = "a-luh-saw-ruhs",
                    Meaning = "Different Lizard",
                    Era = "Late Jurassic Period",
                    Group = "Theropod",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "The fiercest hunter of the Jurassic",
                    Length = "30 feet",
                    Height = "10 feet",
                    Weight = "2500kg",
                    Speed = "50km/h",
                    Strength = 78,
                    ImageFile = "allosaurus.png",
                    AboutText = "Allosaurus was a large carnivorous dinosaur that lived around 145 to 155 million years ago during the Late Jurassic Period. It was one of the top predators of its time, hunting large herbivorous dinosaurs such as Stegosaurus and younger sauropods across North America and Europe.",
                    KeyFeaturesText = "Allosaurus had a large skull with sharp, serrated teeth and powerful jaws designed for slicing flesh. Its arms were strong with three-fingered hands, and its long muscular legs allowed it to move quickly for its size. A flexible neck and balanced tail helped it strike at prey effectively.",
                    LifeEnvironmentText = "Allosaurus lived in forested floodplains, river valleys, and semi-arid environments. These ecosystems were home to large herbivores, providing hunting opportunities. It shared its habitat with other predators but was often the dominant large theropod at the top of the food chain.",
                    BehaviourText = "Allosaurus is believed to have been an active predator and possibly an opportunistic scavenger. Allosaurus was likely a solitary hunter, using ambush tactics to take down prey much larger than itself.",
                    FunFactsText = "• Allosaurus was one of the most common large predators of the Jurassic.\n• It had serrated teeth that worked like steak knives for cutting flesh.\n• Some fossils show evidence of injuries, suggesting frequent combat.\n• It may have used its upper jaw like a hatchet-style striking weapon.\n• Allosaurus was constantly shedding and replacing its teeth."
                },
                new Dinosaur
                {
                    Name = "Parasaurolophus",
                    Pronunciation = "peh-ruh-saw-raa-luh-fuhs",
                    Meaning = "Near-Crested Lizard",
                    Era = "Late Cretaceous Period",
                    Group = "Hadrosaur",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "A dinosaur with a built-in trumpet",
                    Length = "32 feet",
                    Height = "15 feet",
                    Weight = "4500kg",
                    Speed = "45km/h",
                    Strength = 35,
                    ImageFile = "parasaurolophus.png",
                    AboutText = "Parasaurolophus was a large herbivorous dinosaur that lived around 73 to 76 million years ago in what is now North America. It is famous for its long, curved crest on its head, which may have been used for communication, display, and sound resonance.",
                    KeyFeaturesText = "Parasaurolophus had a long tube-like crest that extended backward from its skull, which helped amplify sounds for communication. It had a duck-billed mouth adapted for cropping plants and hundreds of teeth arranged in rows for grinding vegetation. Its strong hind legs allowed it to move quickly when needed.",
                    LifeEnvironmentText = "Parasaurolophus lived in forests, river valleys, and coastal plains filled with lush vegetation. It shared its environment with other hadrosaurs, ceratopsians, and large predators like Tyrannosaurus Rex. It likely roamed large areas in search of fresh vegetation.",
                    BehaviourText = "Parasaurolophus is believed to have lived in herds for protection against predators. It likely used its crest to produce low-frequency sounds to communicate with others in its group. It was a peaceful grazer, feeding on leaves, plants, and aquatic vegetation.",
                    FunFactsText = "• Its crest may have worked like a natural trumpet.\n• Scientists can recreate possible sounds it made using skull models.\n• It could both walk on two legs and four legs.\n• The crest on its head could grow up to 6 foot, being as big as a man!\n• Parasaurolophus had no real weapons to defend itself — its only defence was speed, senses, and safety in numbers."
                },
                new Dinosaur
                {
                    Name = "Argentinosaurus",
                    Pronunciation = "aar-juhn-tee-nuh-saw-ruhs",
                    Meaning = "Lizard From Argentina",
                    Era = "Mid Cretaceous Period",
                    Group = "Sauropod",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "One of the largest animals to ever exist",
                    Length = "115 feet",
                    Height = "40 feet",
                    Weight = "90,000kg",
                    Speed = "7km/h",
                    Strength = 65,
                    ImageFile = "argentinosaurus.png",
                    AboutText = "Argentinosaurus was one of the largest land animals ever to exist, living around 94 to 97 million years ago in what is now Argentina. This enormous titanosaur was a plant-eating giant that moved slowly across floodplains, stripping vegetation from tall trees with its massive neck.",
                    KeyFeaturesText = "Argentinosaurus had an incredibly long neck, a massive barrel-shaped body, and thick pillar-like legs to support its enormous weight. Its bones were large but relatively lightweight inside, helping reduce strain. Even its vertebrae were highly adapted for supporting one of the heaviest bodies on land.",
                    LifeEnvironmentText = "Argentinosaurus lived in warm floodplains, forests, and open plains in what is now South America. These environments were home to conifers, ferns, and other plants that could sustain its massive appetite. Due to its size, adult Argentinosaurus had very few predators, such as the Giganotosaurus, though juveniles may have been far more vulnerable.",
                    BehaviourText = "Argentinosaurus likely moved in slow, steady herds or small groups, using its size as protection against predators. It spent most of its time feeding and migrating between vegetation-filled areas. Like other sauropods, it would have needed to consume hundreds of kilograms of plants each day.",
                    FunFactsText = "• Argentinosaurus may have been longer than a basketball court.\n• It is often considered one of the heaviest land animals ever discovered.\n• Its thigh bone alone could be over 2 meters long.\n• Scientists still debate its exact size due to incomplete fossils.\n• It had an endless appetite, eating up to a whopping 1000kg in plant matter each day."
                },
                new Dinosaur
                {
                    Name = "Therizinosaurus",
                    Pronunciation = "theh-rih-zih-nuh-saw-ruhs",
                    Meaning = "Scythe Lizard",
                    Era = "Late Cretaceous Period",
                    Group = "Theropod",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "A giant feathered dinosaur with enormous claws",
                    Length = "32 feet",
                    Height = "15 feet",
                    Weight = "5500kg",
                    Speed = "24km/h",
                    Strength = 58,
                    ImageFile = "therizinosaurus.png",
                    AboutText = "Therizinosaurus was one of the strangest dinosaurs to ever live. It lived around 66 to 70 million years ago during the Late Cretaceous Period in what is now Mongolia. Although it belonged to the same group of dinosaurs as famous meat-eaters like T. Rex, Therizinosaurus evolved into a giant plant eater with a long neck, feathers, and the longest claws of any land animal in history.",
                    KeyFeaturesText = "Therizinosaurus had enormous scythe-like claws on its hands which could grow over 3 feet long. It also had a long neck for reaching vegetation, a wide body for digesting plants, and feathers covering much of its body. Despite its fearsome appearance, its small teeth and beak were adapted for eating leaves, branches, and other vegetation.",
                    LifeEnvironmentText = "Therizinosaurus lived in forests, river valleys, and floodplain environments. These habitats were rich in trees, shrubs, and ferns that provided a proper food source. It shared its environment with predators such as Tarbosaurus, though its huge claws and large size made it a difficult target.",
                    BehaviourText = "Therizinosaurus was a slow-mover that spent most of its day eating vegetation. Its massive claws were probably used for pulling branches closer, defending itself from predators, and displaying dominance. Scientists believe it relied more on intimidation and defence than speed when threatened.",
                    FunFactsText = "• Therizinosaurus looked more like a giant feathered bird than a traditional dinosaur.\n• Its claws were longer than the arm of an average adult human.\n• Scientists originally thought its claws belonged to a giant sea turtle.\n• Despite being related to carnivorous dinosaurs, it evolved into a plant eater.\n• Therizinosaurus had one of the widest bodies of any theropod, giving it a barrel-shaped belly for digesting tough plant matter."
                },
                new Dinosaur
                {
                    Name = "Titanosaurus",
                    Pronunciation = "tai-tan-oh-saw-ruhs",
                    Meaning = "Titanic Lizard",
                    Era = "Late Cretaceous Period",
                    Group = "Sauropod",
                    Diet = "Herbivore",
                    Category = "Land",
                    ShortDescription = "A colossal long-necked giant of the Cretaceous",
                    Length = "57 feet",
                    Height = "16 feet",
                    Weight = "70,000kg",
                    Speed = "5km/h",
                    Strength = 62,
                    ImageFile = "titanosaurus.png",
                    AboutText = "Titanosaurus was a large plant-eating sauropod dinosaur that lived around 70 million years ago during the Late Cretaceous Period in what is now India and parts of Asia. It belonged to a group known as titanosaurs, some of the largest land animals ever to walk the Earth. Although the original Titanosaurus fossils are incomplete, it remains one of the most well-known members of this giant dinosaur family.",
                    KeyFeaturesText = "Titanosaurus had a long neck, a long tail, and a massive barrel-shaped body supported by thick pillar-like legs. Its peg-shaped teeth were ideal for stripping leaves from trees and shrubs. Like many titanosaurs, it may have possessed small bony plates called osteoderms embedded in its skin for added protection.",
                    LifeEnvironmentText = "Titanosaurus lived in floodplains, forests, and open woodlands where food was available. These environments provided ferns, conifers, and flowering plants that shaped its diet. It shared its habitat with carnivorous theropods and other herbivorous dinosaurs, though its large size helped deter most predators such as Abelisaurus.",
                    BehaviourText = "Titanosaurus likely spent most of its day eating vegetation and moving slowly between feeding grounds. Scientists believe it may have travelled in herds for protection, especially when raising young. Its enormous size was its primary defence against predators, while its long neck allowed it to get a wide range of plants.",
                    FunFactsText = "• Titanosaurus had bony armored skin in some places.\n• Its fossils were first found in India in the 1800s.\n• Titanosaurs laid eggs in large nesting colonies.\n• Titanosaurs were the last major group of sauropods before the big extinction event that wiped out the dinosaurs.\n• Titanosaurus is one of the first dinosaurs ever discovered in Asia, making it important to the history of palaeontology."
                },
                new Dinosaur
                {
                    Name = "Titanoboa",
                    Pronunciation = "tai-tan-oh-boh-uh",
                    Meaning = "Titanic Boa",
                    Era = "Mid Paleocene Period",
                    Group = "Snake",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "One of the largest snakes ever to slither on Earth",
                    Length = "42 feet",
                    Width = "3 feet",
                    Weight = "1200kg",
                    Speed = "5km/h",
                    Strength = 75,
                    ImageFile = "titanoboa.png",
                    AboutText = "Titanoboa lived around 58 to 60 million years ago during the Paleocene Epoch in what is now South America. It appeared only a few million years after the extinction of the dinosaurs and thrived in hot tropical rainforests. With a body longer than a school bus and thicker than a grown human, Titanoboa was one of the most powerful predators of its time.",
                    KeyFeaturesText = "Titanoboa had an incredibly long and muscular body that allowed it to overpower prey by wrapping around animals and squeezing until they could no longer breathe. Its powerful jaws could swallow large prey whole, while its flexible skeleton allowed it to consume animals much wider than its own head.",
                    LifeEnvironmentText = "Titanoboa lived in warm, swampy rainforests filled with rivers, lakes, and dense vegetation. These environments were home to giant fish, crocodile-like reptiles, turtles, and other animals that served as prey. As the apex predator of its ecosystem, adult Titanoboa had no enemies.",
                    BehaviourText = "Titanoboa likely spent much of its time in or near water, like modern anacondas. It used ambush tactics, remaining hidden beneath the surface before striking prey with incredible speed. It remains the largest and heaviest snake ever discovered.",
                    FunFactsText = "• A healthy adult human could probably run faster and evade it in a straight path.\n• It lived after the dinosaurs went extinct.\n• It's estimated to be twice as long and 8 times as heavy as a modern anaconda.\n• Scientists estimate it could open its jaws wide enough to swallow a crocodile.\n• Fossils of Titanoboa were discovered in Colombia in 2009."
                },
                new Dinosaur
                {
                    Name = "Deinonychus",
                    Pronunciation = "die-non-ih-kus",
                    Meaning = "Terrible Claw",
                    Era = "Early Cretaceous Period",
                    Group = "Raptor",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "A clever predator with deadly sickle claws",
                    Length = "11 feet",
                    Height = "4 feet",
                    Weight = "80kg",
                    Speed = "55km/h",
                    Strength = 40,
                    ImageFile = "deinonychus.png",
                    AboutText = "Deinonychus was a fast and intelligent carnivorous dinosaur that lived around 110 to 115 million years ago during the Early Cretaceous Period in what is now North America. It was one of the most important dinosaur discoveries ever made because it helped change scientists' view of dinosaurs from slow, sluggish reptiles to active and energetic animals.",
                    KeyFeaturesText = "Deinonychus had a large sickle-shaped claw on each foot that could grow over 5 inches long which was used to grip and wound prey. Its body was covered in feathers, and its stiff tail acted as a counterbalance while running and making sharp turns. It also had strong arms with grasping hands and a mouth filled with sharp, serrated teeth.",
                    LifeEnvironmentText = "Deinonychus lived in forests, floodplains, river valleys, and open woodland environments. These habitats had a variety of prey, including small dinosaurs, mammals, and larger herbivorous dinosaurs such as Tenontosaurus. It shared its ecosystem with other predators such as Acrocanthosaurus but was among the most successful hunters of its region.",
                    BehaviourText = "Deinonychus was an active and agile hunter that relied on its speed, intelligence, and powerful claws to capture prey. Some scientists suggest it may have occasionally hunted in groups, though this remains debated. It likely used its sickle claws to latch onto prey while delivering bites with its sharp teeth.",
                    FunFactsText = "• Deinonychus inspired many of the famous 'raptors' seen in dinosaur movies.\n• Paleontologists theorize these claws were not used for slashing, but to pin prey to the ground.\n• It was covered in feathers, making it closely related to modern birds.\n• Despite having a fearsome reputation, its jaws were relatively weak, so it used its teeth to slash and rip flesh.\n• Its tail was reinforced with stiff tendons, helping it stay balanced during fast movements and sharp turns."
                },
                new Dinosaur
                {
                    Name = "Deinosuchus",
                    Pronunciation = "die-noh-soo-kus",
                    Meaning = "Terrible Crocodile",
                    Era = "Late Cretaceous Period",
                    Group = "Crocodylian",
                    Diet = "Carnivore",
                    Category = "Land",
                    ShortDescription = "A giant crocodilian that hunted dinosaurs",
                    Length = "40 feet",
                    Width = "5 feet",
                    Weight = "8000kg",
                    Speed = "20km/h",
                    Strength = 96,
                    ImageFile = "deinosuchus.png",
                    AboutText = "Deinosuchus was one of the largest crocodilian relatives to ever live. It lived around 73 to 82 million years ago during the Late Cretaceous Period in what is now North America. Larger than most modern crocodiles and alligators, Deinosuchus was an ambush predator that preyed upon dinosaurs that ventured too close to the water's edge.",
                    KeyFeaturesText = "Deinosuchus had a massive armored body covered in thick bony plates called osteoderms. Its enormous jaws were lined with crushing teeth capable of breaking bone and gripping struggling prey. A powerful tail provided propulsion through water, while its sensitive snout helped detect movement from nearby animals. It had a bite force of around 23,000 pounds.",
                    LifeEnvironmentText = "Deinosuchus lived in rivers, swamps, estuaries, and coastal wetlands that stretched across ancient North America. These waterways were home to fish, turtles, marine reptiles, and numerous dinosaurs that came to drink or cross the water. As one of the largest predators in its ecosystem, adult Deinosuchus had no enemies.",
                    BehaviourText = "Deinosuchus was an ambush predator much like modern crocodilians. It spent long periods waiting beneath the water's surface before exploding forward to seize prey with its powerful jaws. Scientists believe it used the same 'death roll' behavior seen in modern crocodiles to tear apart large animals after capture.",
                    FunFactsText = "• Deinosuchus was not a dinosaur but a giant crocodilian.\n• Bite marks matching Deinosuchus teeth have been found on dinosaur bones.\n• Its bite force exceeded that of T. Rex.\n• Some individuals may have lived for more than 50 years.\n• Despite its enormous size, it looked remarkably similar to a modern alligator."
                }
            };
    }
}